# generate_readme.py
import os
from datetime import datetime

# Get all problem folders (ignore README.md and hidden files)
problem_dirs = [d for d in os.listdir('.') if os.path.isdir(d) and not d.startswith('.')]

# Sort problems by most recent (assuming folders created newest last)
problem_dirs.sort(key=os.path.getmtime, reverse=True)

# Generate problem data
problems = []
for d in problem_dirs:
    # Human-readable name
    title = d.split("-", 1)[1].replace("-", " ").title() if "-" in d else d.title()
    slug = d
    url = f"https://leetcode.com/problems/{slug}/"
    problems.append((title, d, url))

# Build README content
readme = f"""# 🚀 LeetCode Progress Tracker

This repository is synced using [LeetSync](https://github.com/LeetSync/LeetSync).  
It contains my accepted solutions to LeetCode problems, organized by problem folder.  
The `README.md` auto-updates using GitHub Actions when new solutions are added.

---

## ✅ Total Problems Solved: {len(problems)}

_Last updated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_

---

## 📂 Recent Submissions

| Problem Name | Folder | LeetCode Link |
|--------------|--------|---------------|
"""

# Add most recent 10 (or all if less)
for title, folder, url in problems[:10]:
    readme += f"| [{title}]({url}) | [`{folder}`]({folder}) | [🔗 Link]({url}) |\n"

readme += "\n---\n> Generated by `generate_readme.py`"

# Write to README.md
with open("README.md", "w", encoding="utf-8") as f:
    f.write(readme)
